### PR TITLE
modify metadata information

### PR DESCRIPTION
**Pull request by JosephineAkello**
Modify introduction message.
Replace social sites(twitter,IG,Github)  links with actual links

### CODE REVIEW

**Comment by TheBeachMaster** [comment]
Looks good to me

**Comment by TheBeachMaster** [comment]
Since metadata is being changed, maybe in one branch the following changes can be made:
 - [ ] Site name for PWA
https://github.com/Tambua-WomenInTech-Blog/womenintechblog/blob/0f3c1ecdbd3c2e4233d1e11b7997e3fb2ce7b93e/gatsby-config.js#L43-L44
- [ ] Preferred Theme Color on Mobile (PWA stuff) > See [Color Picker](https://duckduckgo.com/?q=color+picker&ia=answer), see [what theme and background colors](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs) are 
https://github.com/Tambua-WomenInTech-Blog/womenintechblog/blob/0f3c1ecdbd3c2e4233d1e11b7997e3fb2ce7b93e/gatsby-config.js#L46-L47

**Review by TheBeachMaster — CHANGES_REQUESTED** [review]
Since metadata is being changed, maybe in one branch the following changes can be made:
 - [ ] Site name for PWA
https://github.com/Tambua-WomenInTech-Blog/womenintechblog/blob/0f3c1ecdbd3c2e4233d1e11b7997e3fb2ce7b93e/gatsby-config.js#L43-L44
- [ ] Preferred Theme Color on Mobile (PWA stuff) > See [Color Picker](https://duckduckgo.com/?q=color+picker&ia=answer), see [what theme and background colors](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs) are 
https://github.com/Tambua-WomenInTech-Blog/womenintechblog/blob/0f3c1ecdbd3c2e4233d1e11b7997e3fb2ce7b93e/gatsby-config.js#L46-L47

**Comment by JosephineAkello** [comment]
* [ ]  Preferred Theme Color on Mobile (PWA stuff) > See [Color Picker](https://duckduckgo.com/?q=color+picker&ia=answer), see [what theme and background colors](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs) are
>   https://github.com/Tambua-WomenInTech-Blog/womenintechblog/blob/0f3c1ecdbd3c2e4233d1e11b7997e3fb2ce7b93e/gatsby-config.js#L46-L47

@TheBeachMaster Is it ideal we change the theme color after creating the logo? Because it goes hand in hand with the logo color

**Comment by TheBeachMaster** [comment]
> * [ ]   Preferred Theme Color on Mobile (PWA stuff) > See [Color Picker](https://duckduckgo.com/?q=color+picker&ia=answer), see [what theme and background colors](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs) are
> 
> > https://github.com/Tambua-WomenInTech-Blog/womenintechblog/blob/0f3c1ecdbd3c2e4233d1e11b7997e3fb2ce7b93e/gatsby-config.js#L46-L47
> 
> @TheBeachMaster Is it ideal we change the theme color after creating the logo? Because it goes hand in hand with the logo color

The theme color could be one of the colors that makes up the logo...  🤔 
Ideally it should contrast with the page. And in most cases, it should be same as the bg color.

There can only be a limited number of colors that make up the logo 🤔

**Pull request merged**
