### PR TITLE
add new author

### PR DESCRIPTION
**Pull request by 75pollet**

### CODE REVIEW

**Comment by TheBeachMaster** [comment]
Hmmm ... Shouldn't this PR come with a blog as well.

If merged, when the new author link is shown, the blogs for this author will be empty... 🤔

**Comment by 75pollet** [comment]
@TheBeachMaster I didn't realize it has to come with a blog. I'll add it to this PR.

**Comment by TheBeachMaster** [comment]
Only for the first blog

**Comment by JosephineAkello** [comment]
> Hmmm ... Shouldn't this come with a PR with a blog as well.
> 
> If merged, when the new author link is shown the blogs for this author will be empty...

probably we can include this in the READMe as well

**Review by JosephineAkello — APPROVED** [review]

**Comment by 75pollet** [comment]
I've added the blog in a separate PR

**Pull request merged**
