### PR TITLE
Blog/maureen josephine/online learning sites

### PR DESCRIPTION
**Pull request by JosephineAkello**
- A blog post that provide links to various online learning sites

### CODE REVIEW

**Review by TheBeachMaster — COMMENTED** [review]
In the links for the blog add the links in this format -square brackets and parentheses-`[fireship](https://fireship.io)`

**Review by TheBeachMaster — APPROVED** [review]

**Comment by JosephineAkello** [comment]
> In the links for the blog add the links in this format -square brackets and parentheses-`[fireship](https://fireship.io)`

@TheBeachMaster Cool, making the adjustments

**Comment by JosephineAkello** [comment]
@TheBeachMaster Changes made as requested. Kindly review once more

**Review by TheBeachMaster — APPROVED** [review]
LGTM.

You could add https://www.codingame.com/home as well

**Pull request merged**
